# Generated by Django 4.2 on 2023-04-26 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_number', models.IntegerField()),
                ('street', models.CharField(max_length=100)),
                ('taluk', models.TextField(max_length=50)),
                ('district', models.TextField(max_length=50)),
                ('state', models.TextField(max_length=20)),
                ('pin', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('speciality', models.CharField(max_length=50)),
                ('mobile_number', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='PatientVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('mobile_number', models.BigIntegerField()),
                ('DOB', models.DateTimeField()),
                ('reason', models.CharField(max_length=50)),
            ],
        ),
    ]
