# Generated by Django 4.2 on 2023-04-26 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientvisit',
            name='address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='opd.address'),
        ),
        migrations.AddField(
            model_name='patientvisit',
            name='doctor',
            field=models.ManyToManyField(to='opd.doctor'),
        ),
    ]
