# Generated by Django 4.2 on 2023-04-26 15:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0002_patientvisit_address_patientvisit_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientvisit',
            name='visted',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
