# Generated by Django 4.2 on 2023-04-27 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient_info', '0002_patient_address'),
        ('opd', '0003_patientvisit_visted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientvisit',
            name='DOB',
        ),
        migrations.RemoveField(
            model_name='patientvisit',
            name='address',
        ),
        migrations.RemoveField(
            model_name='patientvisit',
            name='mobile_number',
        ),
        migrations.RemoveField(
            model_name='patientvisit',
            name='name',
        ),
        migrations.AddField(
            model_name='patientvisit',
            name='patent_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patient_info.patient'),
        ),
    ]
