# Generated by Django 4.2 on 2023-04-27 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0005_rename_patent_name_patientvisit_patient_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientvisit',
            old_name='visted',
            new_name='visited',
        ),
    ]
