# Generated by Django 4.2 on 2023-04-27 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_number', models.TextField(blank=True, max_length=10, null=True)),
                ('street_name', models.TextField(blank=True, max_length=20, null=True)),
                ('area_or_village', models.TextField(max_length=20)),
                ('taluk', models.TextField(max_length=20)),
                ('district', models.TextField(max_length=20)),
                ('pin', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=30)),
                ('mobile_number', models.BigIntegerField(max_length=12)),
                ('DOB', models.DateField()),
                ('blood_group', models.TextField(max_length=4)),
            ],
        ),
    ]
