# Generated by Django 4.2 on 2023-04-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_info', '0002_patient_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='mobile_number',
            field=models.BigIntegerField(),
        ),
    ]
